# Generated by Django 4.2.6 on 2024-03-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagmodel',
            old_name='name',
            new_name='title',
        ),
    ]
